version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskhub_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: taskhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskhub_network

  app:
    build: .
    container_name: taskhub_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: taskhub
      APP_PORT: 8080
    networks:
      - taskhub_network

volumes:
  postgres_data:

networks:
  taskhub_network:
    driver: bridge